services:
  postgres:
    container_name: proposal-postgresql
    image: postgres
    environment:
      POSTGRES_USER: cass
      POSTGRES_PASSWORD: password
      POSTGRES_DB:
      PG_DATA: /var/lib/postgresql/data
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: unless-stopped

volumes:
  postgres: