spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/proposaldb
    username: cass
    password: password
  jpa:
    hibernate:
      ddl-auto: update

# Hibernate automatically detects the SQL dialect for PostgreSQL
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

