spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/proposaldb
    username: cass
    password: password
  jpa:
    hibernate:
      ddl-auto: create-drop
  rabbitmq:
    host: localhost
    port: 5672
    username: cass
    password: password

rabbitmq:
  pending-proposal:
    exchange: pending-proposal.exchange

# Hibernate automatically detects the SQL dialect for PostgreSQL
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect

